// Generated by gencpp from file ethereum_common/AccountToAddressAllowanceRequest.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCEREQUEST_H
#define ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ethereum_common/Address.h>
#include <ethereum_common/Address.h>

namespace ethereum_common
{
template <class ContainerAllocator>
struct AccountToAddressAllowanceRequest_
{
  typedef AccountToAddressAllowanceRequest_<ContainerAllocator> Type;

  AccountToAddressAllowanceRequest_()
    : account()
    , to()  {
    }
  AccountToAddressAllowanceRequest_(const ContainerAllocator& _alloc)
    : account(_alloc)
    , to(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ethereum_common::Address_<ContainerAllocator>  _account_type;
  _account_type account;

   typedef  ::ethereum_common::Address_<ContainerAllocator>  _to_type;
  _to_type to;





  typedef boost::shared_ptr< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AccountToAddressAllowanceRequest_

typedef ::ethereum_common::AccountToAddressAllowanceRequest_<std::allocator<void> > AccountToAddressAllowanceRequest;

typedef boost::shared_ptr< ::ethereum_common::AccountToAddressAllowanceRequest > AccountToAddressAllowanceRequestPtr;
typedef boost::shared_ptr< ::ethereum_common::AccountToAddressAllowanceRequest const> AccountToAddressAllowanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ethereum_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ethereum_common': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/ethereum_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d636755e8c0af9486937ef32e5c3d7a";
  }

  static const char* value(const ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d636755e8c0af94ULL;
  static const uint64_t static_value2 = 0x86937ef32e5c3d7aULL;
};

template<class ContainerAllocator>
struct DataType< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ethereum_common/AccountToAddressAllowanceRequest";
  }

  static const char* value(const ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Address account\n\
Address to\n\
\n\
================================================================================\n\
MSG: ethereum_common/Address\n\
# Ethereum address message\n\
string address\n\
";
  }

  static const char* value(const ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.account);
      stream.next(m.to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccountToAddressAllowanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ethereum_common::AccountToAddressAllowanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "account: ";
    s << std::endl;
    Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.account);
    s << indent << "to: ";
    s << std::endl;
    Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCEREQUEST_H
