// Generated by gencpp from file ethereum_common/Accounts.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ACCOUNTS_H
#define ETHEREUM_COMMON_MESSAGE_ACCOUNTS_H

#include <ros/service_traits.h>


#include <ethereum_common/AccountsRequest.h>
#include <ethereum_common/AccountsResponse.h>


namespace ethereum_common
{

struct Accounts
{

typedef AccountsRequest Request;
typedef AccountsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Accounts
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::Accounts > {
  static const char* value()
  {
    return "031c4bb89ac5ec75fbacab5f05cfa129";
  }

  static const char* value(const ::ethereum_common::Accounts&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::Accounts > {
  static const char* value()
  {
    return "ethereum_common/Accounts";
  }

  static const char* value(const ::ethereum_common::Accounts&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::AccountsRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::Accounts > 
template<>
struct MD5Sum< ::ethereum_common::AccountsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Accounts >::value();
  }
  static const char* value(const ::ethereum_common::AccountsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AccountsRequest> should match 
// service_traits::DataType< ::ethereum_common::Accounts > 
template<>
struct DataType< ::ethereum_common::AccountsRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Accounts >::value();
  }
  static const char* value(const ::ethereum_common::AccountsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::AccountsResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::Accounts > 
template<>
struct MD5Sum< ::ethereum_common::AccountsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Accounts >::value();
  }
  static const char* value(const ::ethereum_common::AccountsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AccountsResponse> should match 
// service_traits::DataType< ::ethereum_common::Accounts > 
template<>
struct DataType< ::ethereum_common::AccountsResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Accounts >::value();
  }
  static const char* value(const ::ethereum_common::AccountsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ACCOUNTS_H
