// Generated by gencpp from file ethereum_common/AccountToAddressAllowance.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCE_H
#define ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCE_H

#include <ros/service_traits.h>


#include <ethereum_common/AccountToAddressAllowanceRequest.h>
#include <ethereum_common/AccountToAddressAllowanceResponse.h>


namespace ethereum_common
{

struct AccountToAddressAllowance
{

typedef AccountToAddressAllowanceRequest Request;
typedef AccountToAddressAllowanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AccountToAddressAllowance
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::AccountToAddressAllowance > {
  static const char* value()
  {
    return "bb0229e808c1117ea0065740cd6cdb83";
  }

  static const char* value(const ::ethereum_common::AccountToAddressAllowance&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::AccountToAddressAllowance > {
  static const char* value()
  {
    return "ethereum_common/AccountToAddressAllowance";
  }

  static const char* value(const ::ethereum_common::AccountToAddressAllowance&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::AccountToAddressAllowanceRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::AccountToAddressAllowance > 
template<>
struct MD5Sum< ::ethereum_common::AccountToAddressAllowanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::AccountToAddressAllowance >::value();
  }
  static const char* value(const ::ethereum_common::AccountToAddressAllowanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AccountToAddressAllowanceRequest> should match 
// service_traits::DataType< ::ethereum_common::AccountToAddressAllowance > 
template<>
struct DataType< ::ethereum_common::AccountToAddressAllowanceRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::AccountToAddressAllowance >::value();
  }
  static const char* value(const ::ethereum_common::AccountToAddressAllowanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::AccountToAddressAllowanceResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::AccountToAddressAllowance > 
template<>
struct MD5Sum< ::ethereum_common::AccountToAddressAllowanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::AccountToAddressAllowance >::value();
  }
  static const char* value(const ::ethereum_common::AccountToAddressAllowanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AccountToAddressAllowanceResponse> should match 
// service_traits::DataType< ::ethereum_common::AccountToAddressAllowance > 
template<>
struct DataType< ::ethereum_common::AccountToAddressAllowanceResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::AccountToAddressAllowance >::value();
  }
  static const char* value(const ::ethereum_common::AccountToAddressAllowanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ACCOUNTTOADDRESSALLOWANCE_H
