// Generated by gencpp from file ethereum_common/AccountsResponse.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ACCOUNTSRESPONSE_H
#define ETHEREUM_COMMON_MESSAGE_ACCOUNTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ethereum_common/Address.h>

namespace ethereum_common
{
template <class ContainerAllocator>
struct AccountsResponse_
{
  typedef AccountsResponse_<ContainerAllocator> Type;

  AccountsResponse_()
    : accounts()  {
    }
  AccountsResponse_(const ContainerAllocator& _alloc)
    : accounts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ethereum_common::Address_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ethereum_common::Address_<ContainerAllocator> >::other >  _accounts_type;
  _accounts_type accounts;





  typedef boost::shared_ptr< ::ethereum_common::AccountsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ethereum_common::AccountsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AccountsResponse_

typedef ::ethereum_common::AccountsResponse_<std::allocator<void> > AccountsResponse;

typedef boost::shared_ptr< ::ethereum_common::AccountsResponse > AccountsResponsePtr;
typedef boost::shared_ptr< ::ethereum_common::AccountsResponse const> AccountsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ethereum_common::AccountsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ethereum_common::AccountsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ethereum_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ethereum_common': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/ethereum_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::AccountsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::AccountsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::AccountsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "031c4bb89ac5ec75fbacab5f05cfa129";
  }

  static const char* value(const ::ethereum_common::AccountsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x031c4bb89ac5ec75ULL;
  static const uint64_t static_value2 = 0xfbacab5f05cfa129ULL;
};

template<class ContainerAllocator>
struct DataType< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ethereum_common/AccountsResponse";
  }

  static const char* value(const ::ethereum_common::AccountsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Address[] accounts\n\
\n\
\n\
================================================================================\n\
MSG: ethereum_common/Address\n\
# Ethereum address message\n\
string address\n\
";
  }

  static const char* value(const ::ethereum_common::AccountsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accounts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccountsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ethereum_common::AccountsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ethereum_common::AccountsResponse_<ContainerAllocator>& v)
  {
    s << indent << "accounts[]" << std::endl;
    for (size_t i = 0; i < v.accounts.size(); ++i)
    {
      s << indent << "  accounts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, indent + "    ", v.accounts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ACCOUNTSRESPONSE_H
