// Generated by gencpp from file ethereum_common/Address.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ADDRESS_H
#define ETHEREUM_COMMON_MESSAGE_ADDRESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ethereum_common
{
template <class ContainerAllocator>
struct Address_
{
  typedef Address_<ContainerAllocator> Type;

  Address_()
    : address()  {
    }
  Address_(const ContainerAllocator& _alloc)
    : address(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;





  typedef boost::shared_ptr< ::ethereum_common::Address_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ethereum_common::Address_<ContainerAllocator> const> ConstPtr;

}; // struct Address_

typedef ::ethereum_common::Address_<std::allocator<void> > Address;

typedef boost::shared_ptr< ::ethereum_common::Address > AddressPtr;
typedef boost::shared_ptr< ::ethereum_common::Address const> AddressConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ethereum_common::Address_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ethereum_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ethereum_common': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/ethereum_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::Address_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::Address_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::Address_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::Address_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::Address_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::Address_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ethereum_common::Address_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bc6398c2d30daa431354525a4683624";
  }

  static const char* value(const ::ethereum_common::Address_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bc6398c2d30daa4ULL;
  static const uint64_t static_value2 = 0x31354525a4683624ULL;
};

template<class ContainerAllocator>
struct DataType< ::ethereum_common::Address_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ethereum_common/Address";
  }

  static const char* value(const ::ethereum_common::Address_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ethereum_common::Address_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ethereum address message\n\
string address\n\
";
  }

  static const char* value(const ::ethereum_common::Address_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ethereum_common::Address_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Address_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ethereum_common::Address_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ethereum_common::Address_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ADDRESS_H
