// Generated by gencpp from file ethereum_common/Allowance.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_ALLOWANCE_H
#define ETHEREUM_COMMON_MESSAGE_ALLOWANCE_H

#include <ros/service_traits.h>


#include <ethereum_common/AllowanceRequest.h>
#include <ethereum_common/AllowanceResponse.h>


namespace ethereum_common
{

struct Allowance
{

typedef AllowanceRequest Request;
typedef AllowanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Allowance
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::Allowance > {
  static const char* value()
  {
    return "e2d262a3aeb417f4eb11856b3be5f1c2";
  }

  static const char* value(const ::ethereum_common::Allowance&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::Allowance > {
  static const char* value()
  {
    return "ethereum_common/Allowance";
  }

  static const char* value(const ::ethereum_common::Allowance&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::AllowanceRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::Allowance > 
template<>
struct MD5Sum< ::ethereum_common::AllowanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Allowance >::value();
  }
  static const char* value(const ::ethereum_common::AllowanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AllowanceRequest> should match 
// service_traits::DataType< ::ethereum_common::Allowance > 
template<>
struct DataType< ::ethereum_common::AllowanceRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Allowance >::value();
  }
  static const char* value(const ::ethereum_common::AllowanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::AllowanceResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::Allowance > 
template<>
struct MD5Sum< ::ethereum_common::AllowanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Allowance >::value();
  }
  static const char* value(const ::ethereum_common::AllowanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::AllowanceResponse> should match 
// service_traits::DataType< ::ethereum_common::Allowance > 
template<>
struct DataType< ::ethereum_common::AllowanceResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Allowance >::value();
  }
  static const char* value(const ::ethereum_common::AllowanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_ALLOWANCE_H
