// Generated by gencpp from file ethereum_common/Approve.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_APPROVE_H
#define ETHEREUM_COMMON_MESSAGE_APPROVE_H

#include <ros/service_traits.h>


#include <ethereum_common/ApproveRequest.h>
#include <ethereum_common/ApproveResponse.h>


namespace ethereum_common
{

struct Approve
{

typedef ApproveRequest Request;
typedef ApproveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Approve
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::Approve > {
  static const char* value()
  {
    return "cf2aa6f2895c288e13b4e136d4e4a5fd";
  }

  static const char* value(const ::ethereum_common::Approve&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::Approve > {
  static const char* value()
  {
    return "ethereum_common/Approve";
  }

  static const char* value(const ::ethereum_common::Approve&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::ApproveRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::Approve > 
template<>
struct MD5Sum< ::ethereum_common::ApproveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Approve >::value();
  }
  static const char* value(const ::ethereum_common::ApproveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::ApproveRequest> should match 
// service_traits::DataType< ::ethereum_common::Approve > 
template<>
struct DataType< ::ethereum_common::ApproveRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Approve >::value();
  }
  static const char* value(const ::ethereum_common::ApproveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::ApproveResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::Approve > 
template<>
struct MD5Sum< ::ethereum_common::ApproveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Approve >::value();
  }
  static const char* value(const ::ethereum_common::ApproveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::ApproveResponse> should match 
// service_traits::DataType< ::ethereum_common::Approve > 
template<>
struct DataType< ::ethereum_common::ApproveResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Approve >::value();
  }
  static const char* value(const ::ethereum_common::ApproveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_APPROVE_H
