// Generated by gencpp from file ethereum_common/BalanceResponse.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_BALANCERESPONSE_H
#define ETHEREUM_COMMON_MESSAGE_BALANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ethereum_common/UInt256.h>

namespace ethereum_common
{
template <class ContainerAllocator>
struct BalanceResponse_
{
  typedef BalanceResponse_<ContainerAllocator> Type;

  BalanceResponse_()
    : balance()  {
    }
  BalanceResponse_(const ContainerAllocator& _alloc)
    : balance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ethereum_common::UInt256_<ContainerAllocator>  _balance_type;
  _balance_type balance;





  typedef boost::shared_ptr< ::ethereum_common::BalanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ethereum_common::BalanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BalanceResponse_

typedef ::ethereum_common::BalanceResponse_<std::allocator<void> > BalanceResponse;

typedef boost::shared_ptr< ::ethereum_common::BalanceResponse > BalanceResponsePtr;
typedef boost::shared_ptr< ::ethereum_common::BalanceResponse const> BalanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ethereum_common::BalanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ethereum_common::BalanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ethereum_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ethereum_common': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/ethereum_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::BalanceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::BalanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::BalanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91627563a1e35c16c10754661905461e";
  }

  static const char* value(const ::ethereum_common::BalanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91627563a1e35c16ULL;
  static const uint64_t static_value2 = 0xc10754661905461eULL;
};

template<class ContainerAllocator>
struct DataType< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ethereum_common/BalanceResponse";
  }

  static const char* value(const ::ethereum_common::BalanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "UInt256 balance\n\
\n\
================================================================================\n\
MSG: ethereum_common/UInt256\n\
# 256bit unisgned integer\n\
string uint256\n\
";
  }

  static const char* value(const ::ethereum_common::BalanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.balance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BalanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ethereum_common::BalanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ethereum_common::BalanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "balance: ";
    s << std::endl;
    Printer< ::ethereum_common::UInt256_<ContainerAllocator> >::stream(s, indent + "  ", v.balance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_BALANCERESPONSE_H
