// Generated by gencpp from file ethereum_common/BlockNumber.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_BLOCKNUMBER_H
#define ETHEREUM_COMMON_MESSAGE_BLOCKNUMBER_H

#include <ros/service_traits.h>


#include <ethereum_common/BlockNumberRequest.h>
#include <ethereum_common/BlockNumberResponse.h>


namespace ethereum_common
{

struct BlockNumber
{

typedef BlockNumberRequest Request;
typedef BlockNumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BlockNumber
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::BlockNumber > {
  static const char* value()
  {
    return "9ea9c5dc974a67358629419455d31fec";
  }

  static const char* value(const ::ethereum_common::BlockNumber&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::BlockNumber > {
  static const char* value()
  {
    return "ethereum_common/BlockNumber";
  }

  static const char* value(const ::ethereum_common::BlockNumber&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::BlockNumberRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::BlockNumber > 
template<>
struct MD5Sum< ::ethereum_common::BlockNumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::BlockNumber >::value();
  }
  static const char* value(const ::ethereum_common::BlockNumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::BlockNumberRequest> should match 
// service_traits::DataType< ::ethereum_common::BlockNumber > 
template<>
struct DataType< ::ethereum_common::BlockNumberRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::BlockNumber >::value();
  }
  static const char* value(const ::ethereum_common::BlockNumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::BlockNumberResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::BlockNumber > 
template<>
struct MD5Sum< ::ethereum_common::BlockNumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::BlockNumber >::value();
  }
  static const char* value(const ::ethereum_common::BlockNumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::BlockNumberResponse> should match 
// service_traits::DataType< ::ethereum_common::BlockNumber > 
template<>
struct DataType< ::ethereum_common::BlockNumberResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::BlockNumber >::value();
  }
  static const char* value(const ::ethereum_common::BlockNumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_BLOCKNUMBER_H
