// Generated by gencpp from file ethereum_common/TransferEvent.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_TRANSFEREVENT_H
#define ETHEREUM_COMMON_MESSAGE_TRANSFEREVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ethereum_common/Address.h>
#include <ethereum_common/Address.h>
#include <ethereum_common/UInt256.h>

namespace ethereum_common
{
template <class ContainerAllocator>
struct TransferEvent_
{
  typedef TransferEvent_<ContainerAllocator> Type;

  TransferEvent_()
    : args_from()
    , args_to()
    , args_value()  {
    }
  TransferEvent_(const ContainerAllocator& _alloc)
    : args_from(_alloc)
    , args_to(_alloc)
    , args_value(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ethereum_common::Address_<ContainerAllocator>  _args_from_type;
  _args_from_type args_from;

   typedef  ::ethereum_common::Address_<ContainerAllocator>  _args_to_type;
  _args_to_type args_to;

   typedef  ::ethereum_common::UInt256_<ContainerAllocator>  _args_value_type;
  _args_value_type args_value;





  typedef boost::shared_ptr< ::ethereum_common::TransferEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ethereum_common::TransferEvent_<ContainerAllocator> const> ConstPtr;

}; // struct TransferEvent_

typedef ::ethereum_common::TransferEvent_<std::allocator<void> > TransferEvent;

typedef boost::shared_ptr< ::ethereum_common::TransferEvent > TransferEventPtr;
typedef boost::shared_ptr< ::ethereum_common::TransferEvent const> TransferEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ethereum_common::TransferEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ethereum_common::TransferEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ethereum_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ethereum_common': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/ethereum_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::TransferEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ethereum_common::TransferEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::TransferEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ethereum_common::TransferEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::TransferEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ethereum_common::TransferEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ethereum_common::TransferEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35f272b72902fee74cbfac3183ab4ae1";
  }

  static const char* value(const ::ethereum_common::TransferEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35f272b72902fee7ULL;
  static const uint64_t static_value2 = 0x4cbfac3183ab4ae1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ethereum_common::TransferEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ethereum_common/TransferEvent";
  }

  static const char* value(const ::ethereum_common::TransferEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ethereum_common::TransferEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Address args_from \n\
Address args_to\n\
UInt256 args_value \n\
\n\
================================================================================\n\
MSG: ethereum_common/Address\n\
# Ethereum address message\n\
string address\n\
\n\
================================================================================\n\
MSG: ethereum_common/UInt256\n\
# 256bit unisgned integer\n\
string uint256\n\
";
  }

  static const char* value(const ::ethereum_common::TransferEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ethereum_common::TransferEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.args_from);
      stream.next(m.args_to);
      stream.next(m.args_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransferEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ethereum_common::TransferEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ethereum_common::TransferEvent_<ContainerAllocator>& v)
  {
    s << indent << "args_from: ";
    s << std::endl;
    Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.args_from);
    s << indent << "args_to: ";
    s << std::endl;
    Printer< ::ethereum_common::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.args_to);
    s << indent << "args_value: ";
    s << std::endl;
    Printer< ::ethereum_common::UInt256_<ContainerAllocator> >::stream(s, indent + "  ", v.args_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_TRANSFEREVENT_H
