// Generated by gencpp from file ethereum_common/TransferFrom.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_TRANSFERFROM_H
#define ETHEREUM_COMMON_MESSAGE_TRANSFERFROM_H

#include <ros/service_traits.h>


#include <ethereum_common/TransferFromRequest.h>
#include <ethereum_common/TransferFromResponse.h>


namespace ethereum_common
{

struct TransferFrom
{

typedef TransferFromRequest Request;
typedef TransferFromResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransferFrom
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::TransferFrom > {
  static const char* value()
  {
    return "bdaad270cecdaddc8d27fbf972359604";
  }

  static const char* value(const ::ethereum_common::TransferFrom&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::TransferFrom > {
  static const char* value()
  {
    return "ethereum_common/TransferFrom";
  }

  static const char* value(const ::ethereum_common::TransferFrom&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::TransferFromRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::TransferFrom > 
template<>
struct MD5Sum< ::ethereum_common::TransferFromRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::TransferFrom >::value();
  }
  static const char* value(const ::ethereum_common::TransferFromRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::TransferFromRequest> should match 
// service_traits::DataType< ::ethereum_common::TransferFrom > 
template<>
struct DataType< ::ethereum_common::TransferFromRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::TransferFrom >::value();
  }
  static const char* value(const ::ethereum_common::TransferFromRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::TransferFromResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::TransferFrom > 
template<>
struct MD5Sum< ::ethereum_common::TransferFromResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::TransferFrom >::value();
  }
  static const char* value(const ::ethereum_common::TransferFromResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::TransferFromResponse> should match 
// service_traits::DataType< ::ethereum_common::TransferFrom > 
template<>
struct DataType< ::ethereum_common::TransferFromResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::TransferFrom >::value();
  }
  static const char* value(const ::ethereum_common::TransferFromResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_TRANSFERFROM_H
