// Generated by gencpp from file ethereum_common/Transfer.msg
// DO NOT EDIT!


#ifndef ETHEREUM_COMMON_MESSAGE_TRANSFER_H
#define ETHEREUM_COMMON_MESSAGE_TRANSFER_H

#include <ros/service_traits.h>


#include <ethereum_common/TransferRequest.h>
#include <ethereum_common/TransferResponse.h>


namespace ethereum_common
{

struct Transfer
{

typedef TransferRequest Request;
typedef TransferResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Transfer
} // namespace ethereum_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ethereum_common::Transfer > {
  static const char* value()
  {
    return "3174e907a7a184dbf8e5563f18f0c467";
  }

  static const char* value(const ::ethereum_common::Transfer&) { return value(); }
};

template<>
struct DataType< ::ethereum_common::Transfer > {
  static const char* value()
  {
    return "ethereum_common/Transfer";
  }

  static const char* value(const ::ethereum_common::Transfer&) { return value(); }
};


// service_traits::MD5Sum< ::ethereum_common::TransferRequest> should match 
// service_traits::MD5Sum< ::ethereum_common::Transfer > 
template<>
struct MD5Sum< ::ethereum_common::TransferRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Transfer >::value();
  }
  static const char* value(const ::ethereum_common::TransferRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::TransferRequest> should match 
// service_traits::DataType< ::ethereum_common::Transfer > 
template<>
struct DataType< ::ethereum_common::TransferRequest>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Transfer >::value();
  }
  static const char* value(const ::ethereum_common::TransferRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ethereum_common::TransferResponse> should match 
// service_traits::MD5Sum< ::ethereum_common::Transfer > 
template<>
struct MD5Sum< ::ethereum_common::TransferResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ethereum_common::Transfer >::value();
  }
  static const char* value(const ::ethereum_common::TransferResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ethereum_common::TransferResponse> should match 
// service_traits::DataType< ::ethereum_common::Transfer > 
template<>
struct DataType< ::ethereum_common::TransferResponse>
{
  static const char* value()
  {
    return DataType< ::ethereum_common::Transfer >::value();
  }
  static const char* value(const ::ethereum_common::TransferResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ETHEREUM_COMMON_MESSAGE_TRANSFER_H
