(cl:defpackage robonomics_liability-srv
  (:use )
  (:export
   "FINISHLIABILITY"
   "<FINISHLIABILITY-REQUEST>"
   "FINISHLIABILITY-REQUEST"
   "<FINISHLIABILITY-RESPONSE>"
   "FINISHLIABILITY-RESPONSE"
   "STARTLIABILITY"
   "<STARTLIABILITY-REQUEST>"
   "STARTLIABILITY-REQUEST"
   "<STARTLIABILITY-RESPONSE>"
   "STARTLIABILITY-RESPONSE"
  ))

