// Generated by gencpp from file robonomics_liability/FinishLiabilityRequest.msg
// DO NOT EDIT!


#ifndef ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYREQUEST_H
#define ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robonomics_liability
{
template <class ContainerAllocator>
struct FinishLiabilityRequest_
{
  typedef FinishLiabilityRequest_<ContainerAllocator> Type;

  FinishLiabilityRequest_()
    : address()
    , success(false)  {
    }
  FinishLiabilityRequest_(const ContainerAllocator& _alloc)
    : address(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FinishLiabilityRequest_

typedef ::robonomics_liability::FinishLiabilityRequest_<std::allocator<void> > FinishLiabilityRequest;

typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityRequest > FinishLiabilityRequestPtr;
typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityRequest const> FinishLiabilityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robonomics_liability

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robonomics_liability': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/robonomics_liability/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26b15e2de4e826d98955e2304f45fe00";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26b15e2de4e826d9ULL;
  static const uint64_t static_value2 = 0x8955e2304f45fe00ULL;
};

template<class ContainerAllocator>
struct DataType< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robonomics_liability/FinishLiabilityRequest";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string address\n\
bool success\n\
";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FinishLiabilityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robonomics_liability::FinishLiabilityRequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYREQUEST_H
