// Generated by gencpp from file robonomics_liability/FinishLiabilityResponse.msg
// DO NOT EDIT!


#ifndef ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYRESPONSE_H
#define ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robonomics_liability
{
template <class ContainerAllocator>
struct FinishLiabilityResponse_
{
  typedef FinishLiabilityResponse_<ContainerAllocator> Type;

  FinishLiabilityResponse_()
    {
    }
  FinishLiabilityResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FinishLiabilityResponse_

typedef ::robonomics_liability::FinishLiabilityResponse_<std::allocator<void> > FinishLiabilityResponse;

typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityResponse > FinishLiabilityResponsePtr;
typedef boost::shared_ptr< ::robonomics_liability::FinishLiabilityResponse const> FinishLiabilityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robonomics_liability

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robonomics_liability': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/robonomics_liability/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robonomics_liability/FinishLiabilityResponse";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FinishLiabilityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robonomics_liability::FinishLiabilityResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITYRESPONSE_H
