// Generated by gencpp from file robonomics_liability/FinishLiability.msg
// DO NOT EDIT!


#ifndef ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITY_H
#define ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITY_H

#include <ros/service_traits.h>


#include <robonomics_liability/FinishLiabilityRequest.h>
#include <robonomics_liability/FinishLiabilityResponse.h>


namespace robonomics_liability
{

struct FinishLiability
{

typedef FinishLiabilityRequest Request;
typedef FinishLiabilityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FinishLiability
} // namespace robonomics_liability


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robonomics_liability::FinishLiability > {
  static const char* value()
  {
    return "26b15e2de4e826d98955e2304f45fe00";
  }

  static const char* value(const ::robonomics_liability::FinishLiability&) { return value(); }
};

template<>
struct DataType< ::robonomics_liability::FinishLiability > {
  static const char* value()
  {
    return "robonomics_liability/FinishLiability";
  }

  static const char* value(const ::robonomics_liability::FinishLiability&) { return value(); }
};


// service_traits::MD5Sum< ::robonomics_liability::FinishLiabilityRequest> should match 
// service_traits::MD5Sum< ::robonomics_liability::FinishLiability > 
template<>
struct MD5Sum< ::robonomics_liability::FinishLiabilityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robonomics_liability::FinishLiability >::value();
  }
  static const char* value(const ::robonomics_liability::FinishLiabilityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robonomics_liability::FinishLiabilityRequest> should match 
// service_traits::DataType< ::robonomics_liability::FinishLiability > 
template<>
struct DataType< ::robonomics_liability::FinishLiabilityRequest>
{
  static const char* value()
  {
    return DataType< ::robonomics_liability::FinishLiability >::value();
  }
  static const char* value(const ::robonomics_liability::FinishLiabilityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robonomics_liability::FinishLiabilityResponse> should match 
// service_traits::MD5Sum< ::robonomics_liability::FinishLiability > 
template<>
struct MD5Sum< ::robonomics_liability::FinishLiabilityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robonomics_liability::FinishLiability >::value();
  }
  static const char* value(const ::robonomics_liability::FinishLiabilityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robonomics_liability::FinishLiabilityResponse> should match 
// service_traits::DataType< ::robonomics_liability::FinishLiability > 
template<>
struct DataType< ::robonomics_liability::FinishLiabilityResponse>
{
  static const char* value()
  {
    return DataType< ::robonomics_liability::FinishLiability >::value();
  }
  static const char* value(const ::robonomics_liability::FinishLiabilityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBONOMICS_LIABILITY_MESSAGE_FINISHLIABILITY_H
