// Generated by gencpp from file robonomics_liability/StartLiability.msg
// DO NOT EDIT!


#ifndef ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITY_H
#define ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITY_H

#include <ros/service_traits.h>


#include <robonomics_liability/StartLiabilityRequest.h>
#include <robonomics_liability/StartLiabilityResponse.h>


namespace robonomics_liability
{

struct StartLiability
{

typedef StartLiabilityRequest Request;
typedef StartLiabilityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartLiability
} // namespace robonomics_liability


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robonomics_liability::StartLiability > {
  static const char* value()
  {
    return "ebc07382abd5516bf503d6260b124af7";
  }

  static const char* value(const ::robonomics_liability::StartLiability&) { return value(); }
};

template<>
struct DataType< ::robonomics_liability::StartLiability > {
  static const char* value()
  {
    return "robonomics_liability/StartLiability";
  }

  static const char* value(const ::robonomics_liability::StartLiability&) { return value(); }
};


// service_traits::MD5Sum< ::robonomics_liability::StartLiabilityRequest> should match 
// service_traits::MD5Sum< ::robonomics_liability::StartLiability > 
template<>
struct MD5Sum< ::robonomics_liability::StartLiabilityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robonomics_liability::StartLiability >::value();
  }
  static const char* value(const ::robonomics_liability::StartLiabilityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robonomics_liability::StartLiabilityRequest> should match 
// service_traits::DataType< ::robonomics_liability::StartLiability > 
template<>
struct DataType< ::robonomics_liability::StartLiabilityRequest>
{
  static const char* value()
  {
    return DataType< ::robonomics_liability::StartLiability >::value();
  }
  static const char* value(const ::robonomics_liability::StartLiabilityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robonomics_liability::StartLiabilityResponse> should match 
// service_traits::MD5Sum< ::robonomics_liability::StartLiability > 
template<>
struct MD5Sum< ::robonomics_liability::StartLiabilityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robonomics_liability::StartLiability >::value();
  }
  static const char* value(const ::robonomics_liability::StartLiabilityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robonomics_liability::StartLiabilityResponse> should match 
// service_traits::DataType< ::robonomics_liability::StartLiability > 
template<>
struct DataType< ::robonomics_liability::StartLiabilityResponse>
{
  static const char* value()
  {
    return DataType< ::robonomics_liability::StartLiability >::value();
  }
  static const char* value(const ::robonomics_liability::StartLiabilityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITY_H
