// Generated by gencpp from file robonomics_liability/StartLiabilityResponse.msg
// DO NOT EDIT!


#ifndef ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITYRESPONSE_H
#define ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robonomics_liability
{
template <class ContainerAllocator>
struct StartLiabilityResponse_
{
  typedef StartLiabilityResponse_<ContainerAllocator> Type;

  StartLiabilityResponse_()
    : success(false)
    , msg()  {
    }
  StartLiabilityResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartLiabilityResponse_

typedef ::robonomics_liability::StartLiabilityResponse_<std::allocator<void> > StartLiabilityResponse;

typedef boost::shared_ptr< ::robonomics_liability::StartLiabilityResponse > StartLiabilityResponsePtr;
typedef boost::shared_ptr< ::robonomics_liability::StartLiabilityResponse const> StartLiabilityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robonomics_liability

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robonomics_liability': ['/home/parallels/energyhack_2018/ws/src/robonomics_comm/robonomics_liability/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e835b04f93d0b30fd8cb71e0967a16db";
  }

  static const char* value(const ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe835b04f93d0b30fULL;
  static const uint64_t static_value2 = 0xd8cb71e0967a16dbULL;
};

template<class ContainerAllocator>
struct DataType< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robonomics_liability/StartLiabilityResponse";
  }

  static const char* value(const ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string msg\n\
\n\
";
  }

  static const char* value(const ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartLiabilityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robonomics_liability::StartLiabilityResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBONOMICS_LIABILITY_MESSAGE_STARTLIABILITYRESPONSE_H
